version: '3'

services:

  web-core:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_ENV=development
    ports:
      - 4000:4000
    volumes:
      - ./:/opt/web-core
    command: ["npm", "run", "start"]

  mongo:
    image: sammlerio/mongo:latest@sha256:c8a1941d19da89eaa84b30276ec350e54f2e80bcd3bdd81f69a8f13070e8b333
    ports:
      - 27017:27017

  auth-service:
    image: sammlerio/auth-service:latest@sha256:ebdc9a2e97a6cfe774aa61a2f0b8fb85c0cfe51906dce8bc4f9b1e36be943650
    ports:
      - "3010:3010"
    environment:
      - PORT=3010
      - MONGODB_DEBUG=false
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
    volumes:
      - ./node_modules/auth-service:/opt/auth-service
    command: ["npm", "run", "start:watch"]
    depends_on:
      - mongo

