version: '3'

services:

  web-core:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_ENV=development
      - S5R_LOG_SERVICE_PORT=3004
      - S5R_AUTH_SERVICE_PORT=3010
    ports:
      - 4000:4000
    volumes:
      - ./:/opt/web-core
    command: ["npm", "run", "start"]

  mongo:
    image: sammlerio/mongo
    ports:
      - 27017:27017
    logging:
      driver: none

  rabbitmq:
    image: sammlerio/rabbitmq
    ports:
      - "8080:15672"
      - "5672:5672"
    logging:
      driver: none


  auth-service:
    image: sammlerio/auth-service
    ports:
      - "3010:3010"
    environment:
      - PORT=3010
      - JWT_SECREAT=foo
      - MONGODB_DEBUG=false
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
    volumes:
      - ./node_modules/auth-service:/opt/auth-service
    command: ["npm", "run", "start:watch"]
    depends_on:
      - mongo

#  log-service:
#    image: sammlerio/log-service
#    ports:3017
#      - "3004:3004"
#    environment:
#    volumes:
#      - ./node_modules/log-service:/opt/log-service
#    command: ["npm", "run", "start:watch"]
#    depends_on:
#      - mongo



